version: '3.8'
services:
  backend:
    build:
      context: .
    ports:
      - "3333:3333"
    env_file:
      - .env
    depends_on:
      - db
  db:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: env.get('DB_PASSWORD')
      MYSQL_DATABASE: env.get('DB_DATABASE'),
      MYSQL_USER: env.get('DB_USER')
      MYSQL_PASSWORD: env.get('DB_PASSWORD')
    ports:
      - "3306:3306"